# Lines of Communication
TAAS_RECV_LOC = 1
# Mirrored Line
TAAS_RECV_REM = 2

# OVS tables used by TaaS in br-tun
TAAS_SEND_UCAST = 30
TAAS_SEND_FLOOD = 31
TAAS_CLASSIFY = 35
TAAS_DST_CHECK = 36
TAAS_SRC_CHECK = 37
TAAS_DST_RESPOND = 38
TAAS_SRC_RESPOND = 39

TYPE_GRE = 'gre'
TYPE_VXLAN = 'vxlan'

TUNNEL_NETWORK_TYPES = [TYPE_VXLAN]
GRE_TUN_LV = 0
VXLAN_TUN_LV = 0

TUN_TABLE = {TYPE_VXLAN: VXLAN_TUN_LV}

TAP_SERVICE_PREFIX = "sr-"